---
- name: Install dependencies
  apt: name={{ item }} state=latest
  with_items:
    - python
    - curl
    - apt-transport-https
    - ca-certificates
    - apparmor

- name: install pip
  shell: curl -sSL https://bootstrap.pypa.io/get-pip.py | python

- name: install docker-compose
  shell: curl -sSL https://github.com/docker/compose/releases/download/1.11.1/run.sh > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

- name: install docker-py
  pip: name=docker-py

- name: adding apt-key
  shell: curl -sSL https://get.docker.com/gpg | apt-key add -

- name: docker package
  shell: curl -sSL https://get.docker.com/ | sh
