galaxy_info:
  author: Alejandro Baez <https://keybase.io/baez>
  description: Install docker with docker-compose for RedHat, Debian, and Suse variants.

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  issue_tracker_url: https://bitbucket.org/a_baez/ansible-role-docker/issues

  license: BSD

  min_ansible_version: 2.0

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If travis integration is cofigured, only notification for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  #github_branch:

  # Below are all platforms currently available. Just uncomment
  # the ones that apply to your role. If you don't see your
  # platform on this list, let us know and we'll get it added!
  #
  platforms:
  - name: Archlinux
    versions:
    - all
  - name: EL
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: opensuse
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: SLES
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: Alpine
    versions:
    - all

  galaxy_tags:
    - docker
    - opensuse
    - fedora
    - redhat
    - centos
    - ubuntu
    - arch
    - alpine

dependencies: []
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
