---

ansible_port: 22
ansible_user: centos
ansible_ssh_pass:
# ansible_ssh_private_key_file ~/.ssh/{{ aws_key_name }}.pem
ansible_ssh_private_key_file: ~/.ssh/ansible_f4rr3ll
ansible_become: true
ansible_connection: ssh